# Site settings
course_name: Filter Banks and Wavelets
course_description: "Fundamentals of multirate signal processing (multirate identities, polyphase representations), perfect reconstruction filter banks (general design procedure, paraunitary filter banks), fundamentals of wavelet analysis (discrete wavelet transforms, multiresolution analysis, wavelet bases, coefficient thresholding and sparsity)."
course_semester: "Fall 2024"

baseurl: "/251c" # the subpath of your site, e.g. /blog/
url: "https://sparsity-group.github.io/" # the base hostname & protocol for your site

schoolname: "University of California, San Diego"
schoolurl: "https://ucsd.edu"
  #twitter_username: username 

address: |
    Department of Electrical and Computer Engineering
    9500 Gilman Dr, MC 0407
    La Jolla, CA 92093

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
